fragment ProblemFields on Problem {
    problemId
    reporter {
      email
      isAdmin
    }
    title
    detail
    locationName
    problemType {
      typeName
      typeThaiName
    }
    currentTags {
      tagName
      tagThaiName
    }
    createdAt
    problemLat
    problemLng
    upvoteCount
    userUpvotes_on_problem {
      userId
    }
    problemImages_on_problem {
      imageUrl
      fileName
      imageType
    }
}

query ListProblems @auth(level: PUBLIC insecureReason: "Change to USER when production") {
  problems(orderBy: [{ upvoteCount: DESC }]) {
    ...ProblemFields 
  }
}

query ListNotCompletedProblems @auth(level: PUBLIC insecureReason: "Change to USER when production") {
  problems(
    where: { currentTags: { tagName: { ne: "Completed" } } },
    orderBy: [{ upvoteCount: DESC }]
  ) {
    ...ProblemFields
  }
}

query ListProblemTypes @auth(level: PUBLIC insecureReason: "This operation is safe to expose to the public") {
  problemTypes {
    problemTypeId
    typeName
    typeThaiName
  }
}

query ListProblemTags @auth(level: PUBLIC insecureReason: "This operation is safe to expose to the public") {
  problemTags {
    problemTagId
    tagName
    tagThaiName
  }
}

query ProblemTypesQuery @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  problemTypes {
    typeName
    typeThaiName
  }
}

query ProblemImageByProblemId($problemId: UUID!) @auth(level: PUBLIC insecureReason: "change to USER when production") {
  problemImages(where: {problemId: {eq: $problemId}}) {
    problemImageId
    problemId
    imageUrl
    fileName
    imageType
    createdAt
  }
}
query ProblemsByTag($TagId: UUID!) @auth(level: PUBLIC insecureReason: "Change to USER when production") {
  problems(where: { currentTags: { problemTagId: { eq: $TagId } } }) {
    problemId
  }
}

query ProblemsByTagAndType($TagId: UUID!, $TypeId: UUID!) @auth(level: PUBLIC insecureReason: "Change to USER when production") {
  problems(where: { currentTags: { problemTagId: { eq: $TagId } }, problemType: { problemTypeId: { eq: $TypeId } } }) {
    ...ProblemFields
  }
}

query ProblemsByTagFull($TagId: UUID!) @auth(level: PUBLIC insecureReason: "Change to USER when production") {
  problems(where: { currentTags: { problemTagId: { eq: $TagId } } }) {
    ...ProblemFields
  }
}

query ProblemsByTypeFull($TypeId: UUID!) @auth(level: PUBLIC insecureReason: "Change to USER when production") {
  problems(where: { problemType: { problemTypeId: { eq: $TypeId } } }) {
    ...ProblemFields
  }
}
