fragment ProblemFields on Problem {
    problemId
    reporter {
      email
      isAdmin
    }
    title
    detail
    locationName
    problemType {
      typeName
      typeThaiName
    }
    currentTags {
      tagName
      tagThaiName
    }
    createdAt
    problemLat
    problemLng
    userUpvotes_on_problem {
      userId
    }
    problemImages_on_problem {
      imageUrl
      fileName
      imageType
    }
}

query ListProblems @auth(level: PUBLIC insecureReason: "Change to USER when production") {
  problems{
    ...ProblemFields
  }
}

query ListNotDoneProblems @auth(level: PUBLIC insecureReason: "Change to USER when production") {
  problems(where: { currentTags: { tagName: { ne: "Completed" } } }) {
    ...ProblemFields
  }
}

query ListProblemTypes @auth(level: PUBLIC insecureReason: "This operation is safe to expose to the public") {
  problemTypes {
    problemTypeId
    typeName
    typeThaiName
  }
}

query ListProblemTags @auth(level: PUBLIC insecureReason: "This operation is safe to expose to the public") {
  problemTags {
    problemTagId
    tagName
    tagThaiName
  }
}

query ProblemTypesQuery @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  problemTypes {
    typeName
    typeThaiName
  }
}

query ProblemImageByProblemId($problemId: UUID!) @auth(level: PUBLIC insecureReason: "change to USER when production") {
  problemImages(where: {problemId: {eq: $problemId}}) {
    problemImageId
    problemId
    imageUrl
    fileName
    imageType
    createdAt
  }
}
query ProblemsByTag($TagId: UUID!) @auth(level: PUBLIC insecureReason: "Change to USER when production") {
  problems(where: { currentTags: { problemTagId: { eq: $TagId } } }) {
    problemId
  }
}
