/*
 * File: firebase_options.dart
 * Description: Default Firebase options for use with Firebase apps on various platforms.
 * Responsibilities: Provides platform-specific configurations for Firebase initialization.
 * Author: App team
 * Course: CMU Fondue
 */

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA92zesisMOQYZAwhgAmzCXvY3ECxNe52o',
    appId: '1:349476512174:web:8961b0a6f7aab26c52283f',
    messagingSenderId: '349476512174',
    projectId: 'cmu-fondue',
    authDomain: 'cmu-fondue.firebaseapp.com',
    storageBucket: 'cmu-fondue.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGw7KU5YjWdJjUbCOONyPvlcEBl5X7fik',
    appId: '1:349476512174:android:b0bc779b537127ee52283f',
    messagingSenderId: '349476512174',
    projectId: 'cmu-fondue',
    storageBucket: 'cmu-fondue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZI3lYb6mD5_MMEsZXF6DQxtRVXe3FCSU',
    appId: '1:349476512174:ios:0921e29eda114a4352283f',
    messagingSenderId: '349476512174',
    projectId: 'cmu-fondue',
    storageBucket: 'cmu-fondue.firebasestorage.app',
    iosBundleId: 'com.example.cmuFondue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZI3lYb6mD5_MMEsZXF6DQxtRVXe3FCSU',
    appId: '1:349476512174:ios:0921e29eda114a4352283f',
    messagingSenderId: '349476512174',
    projectId: 'cmu-fondue',
    storageBucket: 'cmu-fondue.firebasestorage.app',
    iosBundleId: 'com.example.cmuFondue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA92zesisMOQYZAwhgAmzCXvY3ECxNe52o',
    appId: '1:349476512174:web:05ce31e7971142ea52283f',
    messagingSenderId: '349476512174',
    projectId: 'cmu-fondue',
    authDomain: 'cmu-fondue.firebaseapp.com',
    storageBucket: 'cmu-fondue.firebasestorage.app',
  );
}
